-- 달력을 만드는 query문
SELECT 
       MIN(DECODE( TO_CHAR(DATES,'D'), 1, TO_CHAR(DATES, 'DD'))) 일,
       MIN(DECODE( TO_CHAR(DATES,'D'), 2, TO_CHAR(DATES, 'DD'))) 월,
       MIN(DECODE( TO_CHAR(DATES,'D'), 3, TO_CHAR(DATES, 'DD'))) 화,
       MIN(DECODE( TO_CHAR(DATES,'D'), 4, TO_CHAR(DATES, 'DD'))) 수,
       MIN(DECODE( TO_CHAR(DATES,'D'), 5, TO_CHAR(DATES, 'DD'))) 목,
       MIN(DECODE( TO_CHAR(DATES,'D'), 6, TO_CHAR(DATES, 'DD'))) 금,
       MIN(DECODE( TO_CHAR(DATES,'D'), 7, TO_CHAR(DATES, 'DD'))) 토
FROM 
(
    SELECT (MAKE_DATES + LEVEL -1 ) DATES
      FROM ( SELECT TO_DATE('20160101','YYYYMMDD') MAKE_DATES FROM DUAL) 
    CONNECT BY (MAKE_DATES + LEVEL-1) <= LAST_DAY(MAKE_DATES)
)
GROUP BY DECODE(TO_CHAR(DATES,'D'), 1, TO_CHAR(DATES, 'IW')+1, TO_CHAR(DATES, 'IW'))
ORDER BY DECODE(TO_CHAR(DATES,'D'), 1, TO_CHAR(DATES, 'IW')+1, TO_CHAR(DATES, 'IW'))
;

-- 어느 일자가 들어오더라도 해당월의 달력을 보여주는 SQL
SELECT  MIN(DECODE(TO_CHAR(DAY,'D'),1,TO_CHAR(DAY,'IW')+1,TO_CHAR(DAY,'IW'))) 주 
        ,MIN(DECODE(TO_CHAR(DAY,'D'),1,TO_CHAR(DAY,'DD'))) 일
        ,MIN(DECODE(TO_CHAR(DAY,'D'),2,TO_CHAR(DAY,'DD'))) 월
        ,MIN(DECODE(TO_CHAR(DAY,'D'),3,TO_CHAR(DAY,'DD'))) 화
        ,MIN(DECODE(TO_CHAR(DAY,'D'),4,TO_CHAR(DAY,'DD'))) 수
        ,MIN(DECODE(TO_CHAR(DAY,'D'),5,TO_CHAR(DAY,'DD'))) 목
        ,MIN(DECODE(TO_CHAR(DAY,'D'),6,TO_CHAR(DAY,'DD'))) 금
        ,MIN(DECODE(TO_CHAR(DAY,'D'),7,TO_CHAR(DAY,'DD'))) 토
FROM
(
    SELECT TO_DATE(REPLACE((TO_CHAR(LAST_DT,'YYYYMM')||TO_CHAR(LEVEL,'00')),' ',''),'YYYYMMDD') DAY
    FROM 
    (
        SELECT LAST_DAY(TO_DATE('20160115','YYYYMMDD')) LAST_DT FROM DUAL
    )
    CONNECT BY LEVEL <=  LAST_DT - TO_DATE(TO_CHAR(LAST_DT,'YYYYMM')||'01','YYYYMMDD') + 1
)
GROUP BY DECODE(TO_CHAR(DAY,'D'),1,TO_CHAR(DAY,'IW')+1,TO_CHAR(DAY,'IW'))
ORDER BY DECODE(TO_CHAR(DAY,'D'),1,TO_CHAR(DAY,'IW')+1,TO_CHAR(DAY,'IW'))
;

-- 주의 개념이 생각과 다르네!!!
SELECT DAY, TO_CHAR(DAY,'IW') 주, TO_CHAR(DAY,'D') 요일
FROM
(
    SELECT TO_DATE(REPLACE((TO_CHAR(LAST_DT,'YYYYMM')||TO_CHAR(LEVEL,'00')),' ',''),'YYYYMMDD') DAY
    FROM 
    (
        SELECT LAST_DAY(TO_DATE('20160115','YYYYMMDD')) LAST_DT FROM DUAL
    )
    CONNECT BY LEVEL <=  LAST_DT - TO_DATE(TO_CHAR(LAST_DT,'YYYYMM')||'01','YYYYMMDD') + 1
)
;