drop type emp_tab_type;
drop type EMP_OBJ_TYPE;
CREATE OR REPLACE TYPE EMP_OBJ_TYPE AS OBJECT
(
  EMPLOYEE_ID NUMBER(5),
  SALARY NUMBER(10),
  COMMISSION_PCT NUMBER
  )
;
CREATE OR REPLACE TYPE EMP_TAB_TYPE
AS TABLE OF EMP_OBJ_TYPE;
;

SELECT A.DEPARTMENT_NAME, B.EMPLOYEE_ID, B.SALARY, B.COMMISSION_PCT
FROM (
  SELECT D.DEPARTMENT_NAME,
  		CAST(MULTISET(
  		SELECT
  			E.EMPLOYEE_ID, E.SALARY, E.COMMISSION_PCT
  		FROM EMP E
  		WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
   		AND ROWNUM <= 3) AS EMP_TAB_TYPE
   		) AS SAL_EMP
  FROM DEPARTMENTS D) A,
  TABLE(SAL_EMP) B

